# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_stable_marriages <- function(male_prefs, female_prefs, U) {
    .Call(`_stablemarriage_find_stable_marriages`, male_prefs, female_prefs, U)
}

