# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementation of the fundamental algorithm for the stable marriage problem
#'
#' A function that uses a pair of preference tables and runs the Fundamental Algorithm to find a stable matching.
#' 
#' @param male_prefs male preference table (list or dataframe)
#' @param female_prefs female preference table (list or dataframe)
#' @param U string name for undesirable male
#' 
#' @return a stable matching with male names and female values (named character vector)
#' @examples
#' find_stable_marriages(male_prefs3, female_prefs3, "U")
#' 
find_stable_marriages <- function(male_prefs, female_prefs, U) {
    .Call(`_stablemarriage_find_stable_marriages`, male_prefs, female_prefs, U)
}

